theme: jekyll-theme-slate
title: AI+DA - Social Network Analysis
description: AI+DA is a multidisciplinary research group located at Escuela Técnica Superior de Ingeniería de Sistemas Informáticos de la Universidad Politécnica de Madrid. Our main research areas are Machine Learning (Classification, Hidden Markov Models), Decision Support Systems, Computational Intelligence, Evolutionary Computation, Data Mining, Social Network Analysis, Big Data, and Intelligent Systems for Industry. With more than 300 publications and 40 reserach and industrial projects, the group has an outstanding experience in both reserach cooperation and partnership consortium.
show_downloads: "true"
logo: images/aida_logo_leaflet.png
